### ISSUE TITLE
Notes not displayed after mongodb error

### ISSUE THREAD

**Issue by gramakri** [nebulade/meemo#12] opened 2016-06-08 17:07 UTC
```
Jun 08 17:04:38 girish.in docker[1316]: ERROR Internal error [ /app/code/node_modules/connect-lastmile/lib/index.js:37:25 ] 
Jun 08 17:04:38 girish.in docker[1316]: stack: 
Jun 08 17:04:38 girish.in docker[1316]:   """
Jun 08 17:04:38 girish.in docker[1316]:     HttpError: Internal error
Jun 08 17:04:38 girish.in docker[1316]:         at /app/code/src/routes.js:159:32
Jun 08 17:04:38 girish.in docker[1316]:         at /app/code/src/things.js:240:35
Jun 08 17:04:38 girish.in docker[1316]:         at /app/code/node_modules/mongodb/lib/collection.js:503:20
Jun 08 17:04:38 girish.in docker[1316]:         at /app/code/node_modules/mongodb/lib/collection.js:617:26
Jun 08 17:04:38 girish.in docker[1316]:         at handleCallback (/app/code/node_modules/mongodb/lib/utils.js:96:12)
Jun 08 17:04:38 girish.in docker[1316]:         at resultHandler (/app/code/node_modules/mongodb/lib/bulk/ordered.js:412:11)
Jun 08 17:04:38 girish.in docker[1316]:         at Server.insert (/app/code/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1367:40)
Jun 08 17:04:38 girish.in docker[1316]:         at Server.insert (/app/code/node_modules/mongodb/lib/server.js:340:17)
Jun 08 17:04:38 girish.in docker[1316]:         at executeCommands (/app/code/node_modules/mongodb/lib/bulk/ordered.js:460:23)
Jun 08 17:04:38 girish.in docker[1316]:         at OrderedBulkOperation.execute (/app/code/node_modules/mongodb/lib/bulk/ordered.js:513:10)
Jun 08 17:04:38 girish.in docker[1316]:   """
Jun 08 17:04:38 girish.in docker[1316]: name:          HttpError
Jun 08 17:04:38 girish.in docker[1316]: status:        500
Jun 08 17:04:38 girish.in docker[1316]: message:       Internal error
Jun 08 17:04:38 girish.in docker[1316]: internalError: 
Jun 08 17:04:38 girish.in docker[1316]:   """
Jun 08 17:04:38 girish.in docker[1316]:     name:    MongoError
Jun 08 17:04:38 girish.in docker[1316]:     message: topology was destroyed
Jun 08 17:04:38 girish.in docker[1316]:     stack: 
Jun 08 17:04:38 girish.in docker[1316]:       """
Jun 08 17:04:38 girish.in docker[1316]:         MongoError: topology was destroyed
Jun 08 17:04:38 girish.in docker[1316]:             at Server.insert (/app/code/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1367:49)
Jun 08 17:04:38 girish.in docker[1316]:             at Server.insert (/app/code/node_modules/mongodb/lib/server.js:340:17)
Jun 08 17:04:38 girish.in docker[1316]:             at executeCommands (/app/code/node_modules/mongodb/lib/bulk/ordered.js:460:23)
Jun 08 17:04:38 girish.in docker[1316]:             at OrderedBulkOperation.execute (/app/code/node_modules/mongodb/lib/bulk/ordered.js:513:10)
Jun 08 17:04:38 girish.in docker[1316]:             at bulkWrite (/app/code/node_modules/mongodb/lib/collection.js:615:8)
Jun 08 17:04:38 girish.in docker[1316]:             at Collection.insertMany (/app/code/node_modules/mongodb/lib/collection.js:502:44)
Jun 08 17:04:38 girish.in docker[1316]:             at Collection.insert (/app/code/node_modules/mongodb/lib/collection.js:789:15)
Jun 08 17:04:38 girish.in docker[1316]:             at /app/code/src/things.js:239:22
Jun 08 17:04:38 girish.in docker[1316]:             at /app/code/node_modules/async/lib/async.js:52:16
Jun 08 17:04:38 girish.in docker[1316]:             at iterate (/app/code/node_modules/async/lib/async.js:260:24)
Jun 08 17:04:38 girish.in docker[1316]:       """
Jun 08 17:04:38 girish.in docker[1316]:   """
```

**Comment by nebulade** [comment] 2016-06-16 08:26
Seems to happen if we write to the collection but just lost the connection to the mongo instance.
Connection options might help as suggested http://stackoverflow.com/questions/29959602/mongoerror-topology-was-destroyed-sailsjs/29969547#29969547

**Comment by nebulade** [comment] 2016-11-04 14:40
Closing for now, can't reproduce for now. Once mongodb is up and running again, notes are again displayed normally. 

Please reopen when it happens again.

**Comment by nebulade** [comment] 2017-02-17 11:28
This came up again

**Comment by nebulade** [comment] 2018-11-29 15:31
Closing due to inactivity

**Closed by nebulade** 2018-11-29 15:31 UTC
