### ISSUE TITLE
Incorrect markdown?

### ISSUE THREAD

**Issue by foorb** [nebulade/meemo#46] opened 2016-12-03 02:25 UTC
markdown code highlighting seems to be wrong:

![2016-12-03 03_22_35-guacamoly](https://cloud.githubusercontent.com/assets/14993807/20856126/f3de4544-b907-11e6-9f94-e36465059abe.png)

V

![2016-12-03 03_22_56-guacamoly](https://cloud.githubusercontent.com/assets/14993807/20856131/17112676-b908-11e6-8ab9-2db3f28b056e.png)

**Comment by nebulade** [comment] 2016-12-03 10:22
The different rendering for fenced and inline code blocks looks according to https://markdown-it.github.io/ Besides adding new functionality, I don't really want to change the basic typography. Too many different opinions on that, maybe in the long run custom style sheets for that use-case would be better.

**Comment by nebulade** [comment] 2016-12-03 10:22
Closing for now, please reopen if your issue was actually regarding something else

**Comment by foorb** [comment] 2016-12-03 12:17
hm...correct would be the following:

![2016-12-03 13_12_32-markdown-it demo](https://cloud.githubusercontent.com/assets/14993807/20859285/523eb6e4-b95a-11e6-8e07-19bd6c72d479.png)

Probably you can tell or help me where I can change the rendering? I'm not that skilled with nodejs.

**Comment by nebulade** [comment] 2016-12-03 12:34
I am struggling to see what the issue is then. Maybe you can explain what is rendered wrongly. All I can see is block and inline differences, which do look same in your screenshots. But I might be missing the point.

**Comment by foorb** [comment] 2016-12-03 12:42
It makes square brackets and curved brackets around the link and output the link twice.
That shouldn't happen with code highlighting. It should remain as it is.

**Comment by nebulade** [comment] 2016-12-03 12:57
Oh indeed, I have focused on the actual code block visuals. Will reopen.

**Closed** 2016-12-05 14:04 UTC

**Comment by foorb** [comment] 2016-12-05 16:00
👍
