### ISSUE TITLE
"npm i" fails, log attached

### ISSUE THREAD

**Issue by cjrobe** [nebulade/meemo#80] opened 2018-01-23 15:39 UTC
I've attached the whole log also, but here's the display of the command line:

[command-line.txt](https://github.com/nebulade/meemo/files/1656566/command-line.txt)

[npm-debug.log](https://github.com/nebulade/meemo/files/1656550/npm-debug.log)

Thanks for any help.

**Comment by Frankstar** [comment] 2018-01-30 14:32
sry but that way to less information.
even the command-line.txt is missing alot
I never hat a similiar issue - so i would tag this as "not a bug"

But - i try to help you.
which os ? how was node installed ?
how did you install meemo ? 
and so on ...

**Comment by nebulade** [comment] 2018-04-15 07:56
I've updated all severely outdate node modules and I suspect it was due to node-sass modules which should be fixed now, so I will close this. Please reopen with more info as @Frankstar suggested, if it is still an issue.

**Closed by nebulade** 2018-04-15 07:56 UTC
